# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=31, verbose_name='用户名')),
                ('password', models.CharField(max_length=31, verbose_name='密码')),
                ('sex', models.BooleanField(default=1, verbose_name='性别')),
                ('birth', models.DateField(auto_now_add=True, verbose_name='生日')),
                ('udesc', models.TextField(null=True, verbose_name='自我简介')),
                ('head_img', models.ImageField(null=True, upload_to='headimg', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('idDelete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
    ]
