# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='文章标题')),
                ('desc', models.CharField(blank=True, max_length=60, null=True, verbose_name='文章描述')),
                ('contents', models.TextField(verbose_name='正文')),
                ('author', models.CharField(max_length=31, verbose_name='作者')),
                ('icon', models.ImageField(null=True, upload_to='article')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('up_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'tb_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=60, verbose_name='文章类型')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='文章数量')),
                ('f_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ArticleType')),
            ],
            options={
                'db_table': 'tb_type',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='art_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ArticleType'),
        ),
        migrations.AddField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backweb.User'),
        ),
    ]
